version: 0.0
os: linux
# destination에 아티팩트가 unzip된 결과가 생성될 디렉토리명을 넣어준다.
files:
  - source: /
    destination: /home/ubuntu/TEST_5_BE
    overwrite: yes
permissions:
  - object: /home/ubuntu/TEST_5_BE
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: /scripts/deploy.sh
      timeout: 60
      runas: root