version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/TEAM_5_BE
permissions:
  - object: /home/ubuntu/TEAM_5_BE/
    owner: ubuntu
    group: ubuntu

file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: deploy.sh